"""
Document export routes — side-by-side bilingual output.
"""
import logging
from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import PlainTextResponse
from sqlalchemy.orm import Session
from database import get_db
from models import Document, DocStatus

logger = logging.getLogger(__name__)
router = APIRouter(prefix="/api/export", tags=["export"])


@router.get("/{doc_id}/bilingual")
async def export_bilingual(doc_id: str, format: str = "md", db: Session = Depends(get_db)):
    """Export document as side-by-side bilingual markdown."""
    doc = db.query(Document).filter(Document.id == doc_id).first()
    if not doc:
        raise HTTPException(404, "Document not found")
    if doc.status not in (DocStatus.TRANSLATED, DocStatus.INDEXED):
        raise HTTPException(400, f"Document not translated yet. Current: {doc.status.value}")

    source_sections = doc.sections or []
    trans_sections = doc.translated_sections or []

    lines = [
        f"# {doc.original_filename} — Bilingual Export",
        f"*{doc.source_lang.upper()} → {doc.target_lang.upper()} · Powered by GMI Cloud Inference Engine*",
        "",
    ]

    max_sections = max(len(source_sections), len(trans_sections))
    for i in range(max_sections):
        src = source_sections[i] if i < len(source_sections) else None
        tgt = trans_sections[i] if i < len(trans_sections) else None
        heading = src["heading"] if src else (tgt["heading"] if tgt else "")

        lines.append(f"## {heading}")
        lines.append("")

        if src:
            lines.append(f"### {doc.source_lang.upper()}")
            lines.append("")
            lines.append(src["content"])
            lines.append("")

        if tgt:
            lines.append(f"### {doc.target_lang.upper()}")
            lines.append("")
            lines.append(tgt["content"])
            lines.append("")

        lines.append("---")
        lines.append("")

    lines.append("*Generated by DocTransAgent on GMI Cloud Inference Engine*")

    content = "\n".join(lines)
    filename = f"{doc.original_filename.rsplit('.', 1)[0]}_bilingual.{format}"

    return PlainTextResponse(
        content=content,
        media_type="text/markdown",
        headers={"Content-Disposition": f"attachment; filename={filename}"},
    )


@router.get("/{doc_id}/glossary-report")
async def export_glossary_report(doc_id: str, db: Session = Depends(get_db)):
    """Export glossary terms extracted from this document."""
    doc = db.query(Document).filter(Document.id == doc_id).first()
    if not doc:
        raise HTTPException(404, "Document not found")

    from services.glossary_service import get_glossary_dict

    glossary = get_glossary_dict(db, source_lang=doc.source_lang, target_lang=doc.target_lang)

    lines = [
        f"# Glossary Report: {doc.original_filename}",
        f"*{doc.source_lang.upper()} → {doc.target_lang.upper()}*",
        "",
        "| Source Term | Target Term |",
        "|------------|-------------|",
    ]
    for src, tgt in glossary.items():
        lines.append(f"| {src} | {tgt} |")

    return PlainTextResponse(
        content="\n".join(lines),
        media_type="text/markdown",
        headers={"Content-Disposition": f"attachment; filename=glossary_{doc.original_filename}"},
    )
