"""
Document export routes — bilingual PDF, DOCX, and Markdown output.
"""
import io
import logging
from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import Response, PlainTextResponse
from sqlalchemy.orm import Session
from database import get_db
from models import Document, DocStatus

logger = logging.getLogger(__name__)
router = APIRouter(prefix="/api/export", tags=["export"])


def _build_bilingual_content(doc: Document) -> list[dict]:
    """Build a list of {heading, level, source, target} dicts."""
    source_sections = doc.sections or []
    trans_sections = doc.translated_sections or []
    rows = []
    for i in range(max(len(source_sections), len(trans_sections))):
        src = source_sections[i] if i < len(source_sections) else None
        tgt = trans_sections[i] if i < len(trans_sections) else None
        rows.append({
            "heading": src["heading"] if src else (tgt["heading"] if tgt else ""),
            "level": src["level"] if src else (tgt["level"] if tgt else 1),
            "source": src["content"] if src else "",
            "target": tgt["content"] if tgt else "",
        })
    return rows


@router.get("/{doc_id}/bilingual")
async def export_bilingual(doc_id: str, format: str = "md", db: Session = Depends(get_db)):
    """Export document as side-by-side bilingual markdown."""
    doc = db.query(Document).filter(Document.id == doc_id).first()
    if not doc:
        raise HTTPException(404, "Document not found")
    if doc.status not in (DocStatus.TRANSLATED, DocStatus.INDEXED):
        raise HTTPException(400, f"Document not translated yet. Current: {doc.status.value}")

    rows = _build_bilingual_content(doc)

    lines = [
        f"# {doc.original_filename} — Bilingual Export",
        f"*{doc.source_lang.upper()} → {doc.target_lang.upper()} · Powered by GMI Cloud Inference Engine*",
        "",
    ]
    for r in rows:
        prefix = "#" * min(r["level"] + 1, 6)
        lines.append(f"{prefix} {r['heading']}")
        lines.append("")
        if r["source"]:
            lines.append(f"### {doc.source_lang.upper()}")
            lines.append("")
            lines.append(r["source"])
            lines.append("")
        if r["target"]:
            lines.append(f"### {doc.target_lang.upper()}")
            lines.append("")
            lines.append(r["target"])
            lines.append("")
        lines.append("---")
        lines.append("")

    lines.append("*Generated by DocTransAgent on GMI Cloud Inference Engine*")
    content = "\n".join(lines)
    filename = f"{doc.original_filename.rsplit('.', 1)[0]}_bilingual.{format}"

    return PlainTextResponse(
        content=content,
        media_type="text/markdown",
        headers={"Content-Disposition": f"attachment; filename={filename}"},
    )


@router.get("/{doc_id}/pdf")
async def export_pdf(doc_id: str, db: Session = Depends(get_db)):
    """Export document as a formatted bilingual PDF."""
    doc = db.query(Document).filter(Document.id == doc_id).first()
    if not doc:
        raise HTTPException(404, "Document not found")
    if doc.status not in (DocStatus.TRANSLATED, DocStatus.INDEXED):
        raise HTTPException(400, f"Document not translated yet. Current: {doc.status.value}")

    rows = _build_bilingual_content(doc)

    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import inch
    from reportlab.lib.colors import HexColor
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, HRFlowable
    from reportlab.lib.enums import TA_LEFT

    buf = io.BytesIO()
    pdf_doc = SimpleDocTemplate(buf, pagesize=A4, leftMargin=0.75*inch, rightMargin=0.75*inch, topMargin=0.6*inch, bottomMargin=0.6*inch)
    styles = getSampleStyleSheet()

    title_style = ParagraphStyle("Title2", parent=styles["Title"], fontSize=16, spaceAfter=6)
    subtitle_style = ParagraphStyle("Sub", parent=styles["Normal"], fontSize=9, textColor=HexColor("#666666"), spaceAfter=12)
    heading_style = ParagraphStyle("H2", parent=styles["Heading2"], fontSize=13, spaceBefore=16, spaceAfter=6)
    label_style = ParagraphStyle("Label", parent=styles["Normal"], fontSize=9, textColor=HexColor("#6366f1"), spaceBefore=8, spaceAfter=2, fontName="Helvetica-Bold")
    body_style = ParagraphStyle("Body", parent=styles["Normal"], fontSize=10, leading=15, spaceAfter=10)
    hr = HRFlowable(width="100%", thickness=0.5, color=HexColor("#e5e7eb"), spaceAfter=10)

    story = []
    story.append(Paragraph(f"{doc.original_filename} — Bilingual Export", title_style))
    story.append(Paragraph(f"{doc.source_lang.upper()} → {doc.target_lang.upper()} · Powered by GMI Cloud", subtitle_style))
    story.append(Spacer(1, 0.2*inch))

    for r in rows:
        story.append(Paragraph(r["heading"], heading_style))
        if r["source"]:
            story.append(Paragraph(doc.source_lang.upper(), label_style))
            story.append(Paragraph(r["source"].replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace("\n", "<br/>"), body_style))
        if r["target"]:
            story.append(Paragraph(doc.target_lang.upper(), label_style))
            story.append(Paragraph(r["target"].replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace("\n", "<br/>"), body_style))
        story.append(hr)

    story.append(Paragraph("*Generated by DocTransAgent on GMI Cloud Inference Engine", subtitle_style))

    pdf_doc.build(story)
    buf.seek(0)

    filename = f"{doc.original_filename.rsplit('.', 1)[0]}_bilingual.pdf"
    return Response(buf.getvalue(), media_type="application/pdf", headers={"Content-Disposition": f"attachment; filename={filename}"})


@router.get("/{doc_id}/docx")
async def export_docx(doc_id: str, db: Session = Depends(get_db)):
    """Export document as a bilingual DOCX file."""
    doc = db.query(Document).filter(Document.id == doc_id).first()
    if not doc:
        raise HTTPException(404, "Document not found")
    if doc.status not in (DocStatus.TRANSLATED, DocStatus.INDEXED):
        raise HTTPException(400, f"Document not translated yet. Current: {doc.status.value}")

    rows = _build_bilingual_content(doc)

    from docx import Document as DocxDoc
    from docx.shared import Pt, Inches, RGBColor
    from docx.enum.text import WD_ALIGN_PARAGRAPH

    docx = DocxDoc()

    title = docx.add_heading(f"{doc.original_filename} — Bilingual Export", level=0)
    p = docx.add_paragraph()
    p.style = docx.styles["Subtitle"]
    run = p.add_run(f"{doc.source_lang.upper()} → {doc.target_lang.upper()} · Powered by GMI Cloud")
    run.font.size = Pt(9)
    run.font.color.rgb = RGBColor(0x66, 0x66, 0x66)

    for r in rows:
        docx.add_heading(r["heading"], level=min(r["level"] + 1, 5))
        if r["source"]:
            label = docx.add_paragraph()
            run = label.add_run(doc.source_lang.upper())
            run.bold = True
            run.font.size = Pt(9)
            run.font.color.rgb = RGBColor(0x63, 0x66, 0xf1)
            docx.add_paragraph(r["source"])
        if r["target"]:
            label = docx.add_paragraph()
            run = label.add_run(doc.target_lang.upper())
            run.bold = True
            run.font.size = Pt(9)
            run.font.color.rgb = RGBColor(0x63, 0x66, 0xf1)
            docx.add_paragraph(r["target"])
        docx.add_paragraph("—" * 40)

    footer = docx.add_paragraph()
    footer.style = docx.styles["Subtitle"]
    run = footer.add_run("*Generated by DocTransAgent on GMI Cloud Inference Engine")
    run.font.size = Pt(8)
    run.font.color.rgb = RGBColor(0x99, 0x99, 0x99)

    buf = io.BytesIO()
    docx.save(buf)
    buf.seek(0)

    filename = f"{doc.original_filename.rsplit('.', 1)[0]}_bilingual.docx"
    return Response(
        buf.getvalue(),
        media_type="application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        headers={"Content-Disposition": f"attachment; filename={filename}"},
    )


@router.get("/{doc_id}/glossary-report")
async def export_glossary_report(doc_id: str, db: Session = Depends(get_db)):
    """Export glossary terms extracted from this document."""
    doc = db.query(Document).filter(Document.id == doc_id).first()
    if not doc:
        raise HTTPException(404, "Document not found")

    from services.glossary_service import get_glossary_dict

    glossary = get_glossary_dict(db, source_lang=doc.source_lang, target_lang=doc.target_lang)

    lines = [
        f"# Glossary Report: {doc.original_filename}",
        f"*{doc.source_lang.upper()} → {doc.target_lang.upper()}*",
        "",
        "| Source Term | Target Term |",
        "|------------|-------------|",
    ]
    for src, tgt in glossary.items():
        lines.append(f"| {src} | {tgt} |")

    return PlainTextResponse(
        content="\n".join(lines),
        media_type="text/markdown",
        headers={"Content-Disposition": f"attachment; filename=glossary_{doc.original_filename}"},
    )
